// Cities in the El Paso, TX metropolitan area
export const cities = [
  {
    slug: 'el-paso-tx',
    name: 'El Paso',
    state: 'TX',
    county: 'El Paso',
    description: 'Premier locksmith and automotive programming services in El Paso, serving the Sun City and surrounding areas.',
    landmarks: [
      'Downtown El Paso',
      'UTEP Campus',
      'El Paso Zoo',
      'Cielo Vista Mall',
      'Fort Bliss',
      'Sunland Park Mall',
      'San Jacinto Plaza',
      'Star on the Mountain'
    ],
    coordinates: { lat: 31.7619, lng: -106.4850 },
    zipCodes: ['79901', '79902', '79903', '79904', '79905', '79906', '79907', '79908', '79910', '79911', '79912', '79915', '79920', '79922', '79924', '79925', '79927', '79928', '79930', '79932', '79934', '79935', '79936', '79938'],
  },
  {
    slug: 'horizon-city-tx',
    name: 'Horizon City',
    state: 'TX',
    county: 'El Paso',
    description: 'Professional locksmith services in Horizon City, east of El Paso.',
    landmarks: [
      'Horizon City Town Hall',
      'Eastlake Marketplace',
      'Desert Hills Golf Course',
      'Horizon Boulevard',
      'Darrington Road',
      'Eastlake Boulevard',
      'Town Center Park',
      'I-10 Corridor'
    ],
    coordinates: { lat: 31.6929, lng: -106.2076 },
    zipCodes: ['79928', '79938'],
  },
  {
    slug: 'socorro-tx',
    name: 'Socorro',
    state: 'TX',
    county: 'El Paso',
    description: 'Expert locksmith services in Socorro, one of the oldest communities in Texas.',
    landmarks: [
      'Socorro Mission',
      'Socorro City Hall',
      'Moon Gate Road',
      'Americas Avenue',
      'Socorro Road',
      'Sparks Park',
      'Rio Vista Road',
      'Old Pueblo Road'
    ],
    coordinates: { lat: 31.6548, lng: -106.3031 },
    zipCodes: ['79927'],
  },
  {
    slug: 'san-elizario-tx',
    name: 'San Elizario',
    state: 'TX',
    county: 'El Paso',
    description: 'Trusted locksmith services in historic San Elizario.',
    landmarks: [
      'San Elizario Presidio Chapel',
      'San Elizario Historic District',
      'Los Portales Museum',
      'Old El Paso County Jail',
      'San Elizario Road',
      'Alameda Avenue',
      'Socorro Road',
      'Historic Plaza'
    ],
    coordinates: { lat: 31.5849, lng: -106.2730 },
    zipCodes: ['79849'],
  },
  {
    slug: 'canutillo-tx',
    name: 'Canutillo',
    state: 'TX',
    county: 'El Paso',
    description: 'Fast, reliable locksmith services in Canutillo and the Upper Valley.',
    landmarks: [
      'Canutillo ISD',
      'Artcraft Road',
      'Doniphan Drive',
      'Canutillo Elementary',
      'Upper Valley',
      'Borderland Road',
      'Canutillo Park',
      'Rio Grande'
    ],
    coordinates: { lat: 31.9138, lng: -106.6005 },
    zipCodes: ['79835'],
  },
  {
    slug: 'anthony-tx',
    name: 'Anthony',
    state: 'TX',
    county: 'El Paso',
    description: 'Professional locksmith services in Anthony, at the TX-NM border.',
    landmarks: [
      'Anthony Town Hall',
      'Anthony ISD',
      'Main Street Anthony',
      'I-10 Corridor',
      'Franklin Street',
      'Washington Street',
      'Anthony Gap',
      'La Union'
    ],
    coordinates: { lat: 32.0040, lng: -106.6056 },
    zipCodes: ['79821'],
  },
  {
    slug: 'clint-tx',
    name: 'Clint',
    state: 'TX',
    county: 'El Paso',
    description: 'Reliable locksmith and key programming services in Clint.',
    landmarks: [
      'Clint ISD',
      'Clint Town Center',
      'Alameda Avenue',
      'I-10 Corridor',
      'Hot Wells',
      'Clint Road',
      'Main Street',
      'Mountain View High School'
    ],
    coordinates: { lat: 31.5924, lng: -106.2241 },
    zipCodes: ['79836'],
  },
  {
    slug: 'fabens-tx',
    name: 'Fabens',
    state: 'TX',
    county: 'El Paso',
    description: 'Expert locksmith services in Fabens and the Lower Valley.',
    landmarks: [
      'Fabens ISD',
      'Main Street Fabens',
      'Fabens High School',
      'I-10 Corridor',
      'Rio Grande',
      'Fabens Road',
      'Camp Street',
      'Alameda Avenue'
    ],
    coordinates: { lat: 31.5082, lng: -106.1588 },
    zipCodes: ['79838'],
  },
  {
    slug: 'vinton-tx',
    name: 'Vinton',
    state: 'TX',
    county: 'El Paso',
    description: 'Professional locksmith solutions for Vinton and the Upper Valley.',
    landmarks: [
      'Vinton Village',
      'Doniphan Drive',
      'Vinton Road',
      'Upper Valley',
      'Western Trails Golf Course',
      'Rio Grande',
      'I-10 Corridor',
      'Westway'
    ],
    coordinates: { lat: 31.9515, lng: -106.6036 },
    zipCodes: ['79821'],
  },
  {
    slug: 'westway-tx',
    name: 'Westway',
    state: 'TX',
    county: 'El Paso',
    description: 'Trusted locksmith services in the Westway community.',
    landmarks: [
      'Westway Community',
      'Doniphan Drive',
      'North Loop Drive',
      'Upper Valley',
      'Rio Grande',
      'Artcraft Road',
      'Montoya Road',
      'Canutillo Area'
    ],
    coordinates: { lat: 31.9700, lng: -106.5800 },
    zipCodes: ['79911'],
  },
  {
    slug: 'sunland-park-nm',
    name: 'Sunland Park',
    state: 'NM',
    county: 'Dona Ana',
    description: 'Premium locksmith services in Sunland Park, just across the NM border.',
    landmarks: [
      'Sunland Park Racetrack & Casino',
      'Sunland Park Mall Area',
      'McNutt Road',
      'Anapra Road',
      'Sunland Park Drive',
      'Santa Teresa',
      'Western Refining',
      'I-10 Corridor'
    ],
    coordinates: { lat: 31.7996, lng: -106.5800 },
    zipCodes: ['88063'],
  },
  {
    slug: 'las-cruces-nm',
    name: 'Las Cruces',
    state: 'NM',
    county: 'Dona Ana',
    description: 'Expert locksmith and automotive programming services in Las Cruces, NM.',
    landmarks: [
      'New Mexico State University',
      'Mesilla Valley Mall',
      'Old Mesilla',
      'Downtown Las Cruces',
      'Organ Mountains',
      'Main Street',
      'Lohman Avenue',
      'Telshor Boulevard'
    ],
    coordinates: { lat: 32.3199, lng: -106.7637 },
    zipCodes: ['88001', '88005', '88007', '88011', '88012'],
  },
  {
    slug: 'chaparral-nm',
    name: 'Chaparral',
    state: 'NM',
    county: 'Dona Ana',
    description: 'Reliable locksmith services for the Chaparral community.',
    landmarks: [
      'Chaparral Middle School',
      'Lisa Drive',
      'County Line',
      'Highway 213',
      'Desert Aire Drive',
      'Oasis Road',
      'Chaparral Park',
      'I-10 Access'
    ],
    coordinates: { lat: 32.0445, lng: -106.4062 },
    zipCodes: ['88081'],
  },
  {
    slug: 'santa-teresa-nm',
    name: 'Santa Teresa',
    state: 'NM',
    county: 'Dona Ana',
    description: 'Professional locksmith services in the Santa Teresa industrial area.',
    landmarks: [
      'Santa Teresa Port of Entry',
      'Santa Teresa Industrial Park',
      'Airport Road',
      'Pete Domenici Highway',
      'McNutt Road',
      'Industrial Zone',
      'Santa Teresa Country Club',
      'Border Highway'
    ],
    coordinates: { lat: 31.8585, lng: -106.6392 },
    zipCodes: ['88008'],
  },
  {
    slug: 'fort-bliss-tx',
    name: 'Fort Bliss',
    state: 'TX',
    county: 'El Paso',
    description: 'Trusted locksmith services for Fort Bliss military personnel and families.',
    landmarks: [
      'Fort Bliss Main Post',
      'William Beaumont Army Medical Center',
      'Freedom Crossing',
      'Biggs Army Airfield',
      'Sgt. Major Blvd',
      'Chaffee Road',
      'Cassidy Gate',
      'Buffalo Soldier Gate'
    ],
    coordinates: { lat: 31.8164, lng: -106.4130 },
    zipCodes: ['79906', '79908', '79916'],
  },
]

// Comprehensive locksmith services
export const services = [
  {
    slug: 'automotive-locksmith',
    name: 'Automotive Locksmith',
    shortDesc: 'Complete car locksmith services including key replacement, programming, and emergency lockout.',
    image: '/images/services/automotive-locksmith.jpg',
    icon: 'Car',
    features: [
      '24/7 emergency car lockout service',
      'All makes and models supported',
      'Mobile service to your location',
      'Transponder key programming',
      'Smart key and key fob replacement',
      'Ignition repair and replacement',
    ],
    keywords: [
      'automotive locksmith El Paso',
      'car locksmith El Paso',
      'vehicle locksmith',
      'auto locksmith near me',
      'mobile car locksmith',
      'cerrajero automotriz El Paso',
    ],
  },
  {
    slug: 'car-key-replacement',
    name: 'Car Key Replacement',
    shortDesc: 'Lost car keys? We cut and program replacement keys for all vehicle makes and models.',
    image: '/images/services/car-key-replacement.jpg',
    icon: 'KeyRound',
    features: [
      'Same-day key replacement',
      'On-site key cutting and programming',
      'Original equipment quality keys',
      'Transponder chip programming',
      'Laser-cut high-security keys',
      'All vehicle brands supported',
    ],
    keywords: [
      'car key replacement El Paso',
      'lost car keys El Paso',
      'car key made',
      'duplicate car key',
      'replacement car key',
      'copia de llaves de carro',
    ],
  },
  {
    slug: 'emergency-lockout',
    name: 'Emergency Lockout Service',
    shortDesc: '24/7 emergency lockout service for vehicles, homes, and businesses in El Paso.',
    image: '/images/services/emergency-lockout.jpg',
    icon: 'Shield',
    features: [
      '24/7 emergency availability',
      '30-minute average response time',
      'Non-destructive entry methods',
      'Car, home, and office lockouts',
      'Licensed and insured technicians',
      'Upfront pricing, no hidden fees',
    ],
    keywords: [
      'emergency locksmith El Paso',
      'locked out of car El Paso',
      'lockout service',
      '24 hour locksmith El Paso',
      'cerrajero de emergencia',
      'locksmith near me',
    ],
  },
  {
    slug: 'ecu-programming',
    name: 'ECU & Computer Programming',
    shortDesc: 'Advanced ECU programming and automotive computer services for all vehicles.',
    image: '/images/services/ecu-programming.jpg',
    icon: 'Cpu',
    features: [
      'Engine Control Unit programming',
      'Body Control Module replacement',
      'Immobilizer system programming',
      'Module repair and replacement',
      'VIN synchronization',
      'Dealer-level diagnostics',
    ],
    keywords: [
      'ECU programming El Paso',
      'car computer programming',
      'ECU repair El Paso',
      'automotive computer',
      'module programming',
      'programacion de computadoras',
    ],
  },
  {
    slug: 'transponder-key-programming',
    name: 'Transponder Key Programming',
    shortDesc: 'Expert transponder chip programming for vehicle security systems.',
    image: '/images/services/transponder-key-programming.jpg',
    icon: 'Radio',
    features: [
      'All transponder types supported',
      'Chip key programming and cloning',
      'Anti-theft system programming',
      'Lost key programming',
      'Additional key programming',
      'Same-day service available',
    ],
    keywords: [
      'transponder key programming El Paso',
      'chip key programming',
      'transponder key',
      'car chip key',
      'programacion de llaves',
      'transponder programming',
    ],
  },
  {
    slug: 'ignition-repair',
    name: 'Ignition Repair & Replacement',
    shortDesc: 'Professional ignition switch repair, replacement, and key extraction.',
    image: '/images/services/ignition-repair.jpg',
    icon: 'Zap',
    features: [
      'Ignition cylinder replacement',
      'Ignition switch repair',
      'Key stuck in ignition removal',
      'Steering column repair',
      'Electronic ignition diagnostics',
      'New key programming included',
    ],
    keywords: [
      'ignition repair El Paso',
      'ignition replacement',
      'key stuck in ignition',
      'ignition switch repair',
      'reparacion de ignicion',
      'car won\'t start',
    ],
  },
  {
    slug: 'residential-locksmith',
    name: 'Residential Locksmith',
    shortDesc: 'Complete home locksmith services including lock installation, rekeying, and security upgrades.',
    image: '/images/services/residential-locksmith.jpg',
    icon: 'Home',
    features: [
      'Lock installation and replacement',
      'Lock rekeying service',
      'Deadbolt installation',
      'Smart lock installation',
      'Home security upgrades',
      'Emergency home lockout service',
    ],
    keywords: [
      'residential locksmith El Paso',
      'home locksmith',
      'house locksmith El Paso',
      'lock change',
      'rekey locks',
      'cerrajero residencial',
    ],
  },
  {
    slug: 'commercial-locksmith',
    name: 'Commercial Locksmith',
    shortDesc: 'Business security solutions including access control, master key systems, and more.',
    image: '/images/services/commercial-locksmith.jpg',
    icon: 'Building',
    features: [
      'Master key system design',
      'Access control systems',
      'Commercial lock installation',
      'High-security locks',
      'Panic bar installation',
      'Office lockout service',
    ],
    keywords: [
      'commercial locksmith El Paso',
      'business locksmith',
      'office locksmith El Paso',
      'master key system',
      'cerrajero comercial',
      'access control',
    ],
  },
  {
    slug: 'lock-rekeying',
    name: 'Lock Rekeying',
    shortDesc: 'Professional lock rekeying for homes and businesses without replacing the entire lock.',
    image: '/images/services/lock-rekeying.jpg',
    icon: 'RefreshCw',
    features: [
      'Residential lock rekeying',
      'Commercial rekeying services',
      'Master key system rekeying',
      'Same-day service available',
      'All lock brands supported',
      'Cost-effective alternative to replacement',
    ],
    keywords: [
      'lock rekeying El Paso',
      'rekey locks',
      'rekey service',
      'change locks El Paso',
      'lock rekey cost',
      'cambio de chapas',
    ],
  },
  {
    slug: 'key-duplication',
    name: 'Key Duplication',
    shortDesc: 'Precision key cutting and duplication for all key types.',
    image: '/images/services/key-duplication.jpg',
    icon: 'Copy',
    features: [
      'Standard key duplication',
      'High-security key cutting',
      'Car key duplication',
      'Laser-cut keys',
      'Restricted key copying',
      'While-you-wait service',
    ],
    keywords: [
      'key duplication El Paso',
      'key copy',
      'key cutting El Paso',
      'duplicate key',
      'copia de llaves',
      'key made',
    ],
  },
  {
    slug: 'smart-key-programming',
    name: 'Smart Key & Keyless Entry',
    shortDesc: 'Smart key programming, keyless entry, and push-to-start system services.',
    image: '/images/services/smart-key-programming.jpg',
    icon: 'Smartphone',
    features: [
      'Smart key programming',
      'Push-to-start system repair',
      'Proximity key programming',
      'Keyless entry troubleshooting',
      'Key fob replacement',
      'Remote start programming',
    ],
    keywords: [
      'smart key programming El Paso',
      'keyless entry El Paso',
      'push to start',
      'proximity key',
      'llave inteligente',
      'key fob programming',
    ],
  },
  {
    slug: 'safe-opening',
    name: 'Safe Opening & Repair',
    shortDesc: 'Professional safe opening, combination changes, and safe repair services.',
    image: '/images/services/safe-opening.jpg',
    icon: 'Lock',
    features: [
      'Safe opening service',
      'Combination changes',
      'Safe repair and maintenance',
      'Digital safe programming',
      'Safe installation',
      'Emergency safe access',
    ],
    keywords: [
      'safe opening El Paso',
      'safe locksmith',
      'safe combination change',
      'locked out of safe',
      'apertura de cajas fuertes',
      'safe opening service',
    ],
  },
  {
    slug: 'module-programming',
    name: 'ECM/TCM/BCM/ABS Module Programming',
    shortDesc: 'Advanced control module programming for ECM, TCM, BCM, and ABS systems - all years, makes, and models.',
    image: '/images/services/module-programming.jpg',
    icon: 'Cpu',
    features: [
      'Engine Control Module (ECM) programming',
      'Transmission Control Module (TCM) programming',
      'Body Control Module (BCM) programming',
      'ABS module programming and repair',
      'All makes and models supported',
      'Latest diagnostic equipment',
    ],
    keywords: [
      'ECM programming El Paso',
      'TCM programming',
      'BCM programming',
      'ABS module El Paso',
      'control module programming',
      'programacion de modulos',
    ],
  },
  {
    slug: 'airbag-reset-crash-module',
    name: 'Airbag Reset & Crash Module Repair',
    shortDesc: 'Professional airbag module reset and crash data clearing after accidents.',
    image: '/images/services/airbag-reset-crash-module.jpg',
    icon: 'Shield',
    features: [
      'Airbag control module reset',
      'Crash data clearing',
      'SRS light diagnostics',
      'Accident data removal',
      'Module replacement and programming',
      'Same-day service available',
    ],
    keywords: [
      'airbag reset El Paso',
      'crash module repair',
      'SRS light El Paso',
      'airbag module',
      'crash data clear',
      'reset de bolsas de aire',
    ],
  },
  {
    slug: 'mercedes-elv-steering-lock-repair',
    name: 'Mercedes ELV Steering Lock Repair (W204)',
    shortDesc: 'Expert Electronic Steering Lock (ELV) repair and replacement for Mercedes-Benz W204 and other models.',
    image: '/images/services/mercedes-elv-steering-lock-repair.jpg',
    icon: 'Car',
    features: [
      'Mercedes W204 ELV repair',
      'Electronic steering lock replacement',
      'ELV module programming',
      'Same-day repair service',
      'All Mercedes models supported',
      'Genuine and aftermarket parts',
    ],
    keywords: [
      'Mercedes ELV repair El Paso',
      'W204 steering lock',
      'electronic steering lock',
      'Mercedes steering lock',
      'ELV replacement',
      'cerrajero Mercedes',
    ],
  },
  {
    slug: 'bmw-frm-repair',
    name: 'BMW FRM Footwell Module Repair',
    shortDesc: 'Professional BMW FRM (Footwell Module) repair and programming services.',
    image: '/images/services/bmw-frm-repair.jpg',
    icon: 'Wrench',
    features: [
      'FRM module repair and replacement',
      'Key programming to FRM',
      'FRM coding and programming',
      'Water damage FRM repair',
      'All BMW models supported',
      'Fast turnaround time',
    ],
    keywords: [
      'BMW FRM repair El Paso',
      'footwell module',
      'BMW key programming',
      'FRM replacement',
      'BMW module repair',
      'reparacion BMW',
    ],
  },
  {
    slug: 'dodge-chrysler-win-module',
    name: 'Dodge/Chrysler WIN Module & FOBIK Programming',
    shortDesc: 'WIN module replacement and FOBIK key programming for Dodge and Chrysler vehicles.',
    image: '/images/services/dodge-chrysler-win-module.jpg',
    icon: 'Radio',
    features: [
      'WIN module replacement',
      'FOBIK key programming',
      'Wireless Ignition Node repair',
      'All Dodge/Chrysler models',
      'Module coding and programming',
      'Same-day service available',
    ],
    keywords: [
      'WIN module El Paso',
      'FOBIK programming',
      'Dodge key programming El Paso',
      'Chrysler key',
      'WIN module replacement',
      'programacion Dodge',
    ],
  },
  {
    slug: 'performance-tuning',
    name: 'Performance Tuning & ECU Remapping',
    shortDesc: 'Professional ECU tuning and remapping services for all makes and models.',
    image: '/images/services/performance-tuning.jpg',
    icon: 'Zap',
    features: [
      'ECU remapping and tuning',
      'Performance chip tuning',
      'Horsepower and torque gains',
      'Fuel economy optimization',
      'Custom tuning solutions',
      'All makes and models',
    ],
    keywords: [
      'ECU tuning El Paso',
      'performance tuning',
      'ECU remapping El Paso',
      'chip tuning',
      'car tuning',
      'performance upgrade El Paso',
    ],
  },
  {
    slug: 'vw-immo-off',
    name: 'VW Immobilizer Off (IMMO OFF)',
    shortDesc: 'Volkswagen and Audi immobilizer delete and IMMO OFF programming services.',
    image: '/images/services/vw-immo-off.jpg',
    icon: 'ShieldOff',
    features: [
      'Immobilizer delete (IMMO OFF)',
      'ECU immobilizer removal',
      'VW and Audi specialists',
      'Swap ECU without keys',
      'Standalone ECU programming',
      'All VW/Audi models',
    ],
    keywords: [
      'IMMO OFF El Paso',
      'VW immobilizer delete',
      'Audi IMMO OFF',
      'immobilizer removal',
      'VW ECU swap',
      'desactivar inmovilizador',
    ],
  },
  {
    slug: 'gm-vats-bypass',
    name: 'GM VATS Bypass & Disable',
    shortDesc: 'Professional GM VATS (Vehicle Anti-Theft System) bypass and disable services.',
    image: '/images/services/gm-vats-bypass.jpg',
    icon: 'Key',
    features: [
      'VATS bypass installation',
      'PassKey system disable',
      'Resistor key bypass',
      'All GM vehicles supported',
      'Permanent bypass solution',
      'No more security lockouts',
    ],
    keywords: [
      'GM VATS bypass El Paso',
      'VATS disable',
      'PassKey bypass',
      'GM security system',
      'VATS lockout',
      'GM anti-theft El Paso',
    ],
  },
  {
    slug: 'dodge-chrysler-vin-swap',
    name: 'Dodge/Chrysler VIN Swap & Programming',
    shortDesc: 'Professional VIN programming and swap services for Dodge and Chrysler control modules.',
    image: '/images/services/dodge-chrysler-vin-swap.jpg',
    icon: 'FileText',
    features: [
      'VIN swap programming',
      'Control module VIN sync',
      'PCM VIN programming',
      'BCM VIN programming',
      'All Dodge/Chrysler models',
      'Dealership-level service',
    ],
    keywords: [
      'VIN swap El Paso',
      'VIN programming',
      'Dodge VIN swap',
      'Chrysler VIN El Paso',
      'module VIN sync',
      'programacion VIN',
    ],
  },
  {
    slug: 'saab-steering-lock-bypass',
    name: 'Saab Steering Lock Bypass',
    shortDesc: 'Expert Saab steering column lock bypass and repair services.',
    image: '/images/services/saab-steering-lock-bypass.jpg',
    icon: 'Unlock',
    features: [
      'Saab steering lock bypass',
      'Column lock repair',
      'Permanent bypass solutions',
      'All Saab models supported',
      'No more stuck steering wheel',
      'Professional installation',
    ],
    keywords: [
      'Saab steering lock El Paso',
      'steering lock bypass',
      'Saab column lock',
      'Saab repair El Paso',
      'steering wheel locked',
      'Saab locksmith',
    ],
  },
]

// Vehicle brands we service
export const vehicleBrands = [
  'Ford', 'Chevrolet', 'GMC', 'Toyota', 'Honda', 'Nissan', 'Dodge', 'Ram',
  'Jeep', 'BMW', 'Mercedes-Benz', 'Audi', 'Volkswagen', 'Lexus', 'Acura',
  'Infiniti', 'Cadillac', 'Lincoln', 'Buick', 'Mazda', 'Subaru', 'Hyundai',
  'Kia', 'Tesla', 'Volvo', 'Jaguar', 'Land Rover', 'Porsche', 'Ferrari',
  'Lamborghini', 'Maserati', 'Bentley', 'Aston Martin', 'McLaren'
]

// Business information
export const businessInfo = {
  name: 'Cerrajero El Paso - Locksmith & Programming',
  tagline: 'Expert Locksmith & Automotive Programming Services in El Paso',
  shortName: 'Cerrajero El Paso',
  phone: '(915) 000-0000',
  phoneRaw: '+19150000000',
  textPhone: '+19150000000',
  email: 'contact@cerrajeroelpaso.com',
  domain: 'https://cerrajeroelpaso.com',
  address: {
    street: 'El Paso',
    city: 'El Paso',
    state: 'TX',
    zip: '79901',
  },
  coordinates: { lat: 31.7619, lng: -106.4850 },
  hours: {
    weekday: '7:00 AM - 9:00 PM',
    saturday: '8:00 AM - 7:00 PM',
    sunday: '9:00 AM - 5:00 PM',
    emergency: '24/7 Emergency Service Available',
  },
  social: {
    facebook: 'https://facebook.com/cerrajeroelpaso',
    instagram: 'https://instagram.com/cerrajeroelpaso',
    twitter: 'https://twitter.com/cerrajeroelpaso',
  },
}
